@echo off
echo Starting Redline Compliance Testing Platform...
echo Checking dependencies...
python -m pip install -r backend\requirements.txt
echo.
echo Running unit tests...
python -m pytest backend\app\tests -v
echo.
echo Launching Redline platform on http://127.0.0.1:8000 ...
python -m uvicorn backend.app.main:app --host 127.0.0.1 --port 8000
